"""add indexes for the task table and dependency table

Revision ID: 24077f4738ab
Revises: 52575d1e52dd
Create Date: 2026-04-19 17:04:01.116926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24077f4738ab'
down_revision: Union[str, Sequence[str], None] = '52575d1e52dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_task_dependencies_depends_on_task_id', 'task_dependencies', ['depends_on_task_id'], unique=False)
    op.create_index('idx_task_dependencies_task_id', 'task_dependencies', ['task_id'], unique=False)
    op.create_index('idx_tasks_status_priority_created_at', 'tasks', ['status', 'priority', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tasks_status_priority_created_at', table_name='tasks')
    op.drop_index('idx_task_dependencies_task_id', table_name='task_dependencies')
    op.drop_index('idx_task_dependencies_depends_on_task_id', table_name='task_dependencies')
    # ### end Alembic commands ###
